### ISSUE TITLE
[Request] Chillout VR Support?

### ISSUE THREAD

**Issue by Alucard0504** [rurre/PumkinsAvatarTools#100]
If I try to use this tool in my CVR project, it seems to cause a compiler error. Can you make a version that is compatible, or have it check for presence of CVR CCK or VRC SDK?

**Comment by rurre** [comment]
It used to be compatible but I haven't really been following cvr updates. What's the error?

**Comment by NotAKidOnSteam** [comment]
PR [93](https://github.com/rurre/PumkinsAvatarTools/pull/93) wasn't ever included with a release package.

**Comment by Alucard0504** [comment]
I get an error for LegacyDestroyer.cs(98,28): error CS0117: 'Helpers' does not contain a definition for 'DestroyMissingScriptsInGameObject'

That seems to be whats hanging things up

**Comment by rurre** [comment]
Will fix this tomorrow

**Comment by rurre** [comment]
Fixed in the next update
