### ISSUE TITLE
Compile warning in unity 2022

### ISSUE THREAD

**Issue by SenkyDragon** [rurre/PumkinsAvatarTools#101]
> Packages\io.github.rurre.pumkinsavatartools\Editor\Destroyers\LegacyDestroyer.cs(68,151): warning CS0618: 'PrefabInstanceStatus.Disconnected' is obsolete: 'PrefabInstanceStatus.Disconnected has been deprecated and is not used. Prefabs can not be in a disconnected state.'

**Comment by rurre** [comment]
Should be fixed in the next update. Thanks
