### ISSUE TITLE
Compile errors in Unity 2022 SDK for VRChat

### ISSUE THREAD

**Issue by BlueAmulet** [rurre/PumkinsAvatarTools#103]
The Unity 2022 SDK for VRChat is now in beta and is causing errors for other people. The cause seems to be because PR https://github.com/rurre/PumkinsAvatarTools/pull/93 is not included in any current release. Manually applying the change to 1.3.9 causes the error to go away.

**Comment by TheWineQueen** [comment]
how would I go about manually applying that?

**Comment by BlueAmulet** [comment]
Open `Packages/io.github.rurre.pumkinsavatartools/Editor/Helpers/PumkinsHelperFunctions.cs`
Find `#elif UNITY_2019` and change to `#elif UNITY_2019_1_OR_NEWER`

**Comment by TheWineQueen** [comment]
thank you so much that helped <3

**Comment by BlueAmulet** [comment]
Should be fixed with the release of 1.4.0
