### ISSUE TITLE
Incompatiblity with the new Constraints VRCSDK? 

### ISSUE THREAD

**Issue by therealnagia** [rurre/PumkinsAvatarTools#109]
Running SDK Version 3.6.2-constraints.3 and I get the following error 
![image](https://github.com/user-attachments/assets/fa7cb4e1-2496-4558-8594-65273064e3eb)

Removing pumpkin from the project allows it to compile and test/upload. 

Not sure how to get more info, please advise.

**Comment by rurre** [comment]
Will fix soon.
