### ISSUE TITLE
When copying over dynamic bones, values need to be divided by 100

### ISSUE THREAD

**Issue by elanhickler** [rurre/PumkinsAvatarTools#11]
Values for radius of colliders and some other things for some reason need to be divded by 100 in order to be the correct size whenever transfer occurs.

**Comment by rurre** [comment]
It could be that your armature scale is 100. It was a common issue with older avatars.
I haven't quite figured out how to fix it since scaling up it down also offsets the position of things

**Comment by elanhickler** [comment]
Is there any way to fix this without CATS? Can you provide any more information on the cause? Is there something I can look at in blender?

**Comment by rurre** [comment]
I'm not entirely sure myself. Need to investigate after the next update

**Comment by elanhickler** [comment]
after next pumpkin tools update or some other update? unity? blender?

**Comment by rurre** [comment]
After the next pumkin tools update

**Comment by elanhickler** [comment]
apparently exporting with cats fixes the issue

**Comment by rurre** [comment]
Fixed in next update
