### ISSUE TITLE
Dynamic bones (Not Found)

### ISSUE THREAD

**Issue by LilUzziii** [rurre/PumkinsAvatarTools#12]
I can't copy dynamic bones because it says they aren't found.
I tried uninstalling and reinstalling dynamic bones 
I also tried using different versions
And i still get the same thing "Dynamic Bones (Not Found)"

**Comment by rurre** [comment]
The current public version has some trouble with dynamic bone detection. 
You can join my discord server linked on the main page and grab a work-in-progress version (from the #wip-releases channel) that should hopefully work for you.
This should also be fixed when the wip version goes public.

**Comment by rurre** [comment]
Try the latest version and tell me if it's fixed for you
