### ISSUE TITLE
[Suggestion] Dynamic Bone Consolidation

### ISSUE THREAD

**Issue by Reploidsham** [rurre/PumkinsAvatarTools#15]
I realized while working on a model that I'd like to be able to consolidate all dynamic bone components to the root to work on so all the dynamic bone components are in one place rather than exploring the armature and potentially missing bones if you happen to have an avatar with a weird bone hierarchy (like how hair can be sometimes, I've missed this damn piece of hair like eight times)
. This reduces the chances I'd lose one. Perhaps a button to move them back to their respective roots would come in handy later, but I'm still rather novice and as far as I'm aware, the location of the components don't matter as long as the root is assigned correctly.

I don't know if this is actually possible, though.

**Comment by rurre** [comment]
Good idea. Might have a different implementation in mind tho.
I'll see what I can do.

**Comment by rurre** [comment]
Hey, I just realized there's a pretty simple alternative to this, you can use the search box and search for a type of component with t:
![Unity_2020-07-31_13-19-16](https://user-images.githubusercontent.com/16716633/89026021-9df21380-d330-11ea-9cd6-900835fc16c3.png)

**Comment by Reploidsham** [comment]
Oh, that's neat! I didn't know that, myself.
