### ISSUE TITLE
Attempting to upload avatar, fails with missing file exception

### ISSUE THREAD

**Issue by Pursec** [rurre/PumkinsAvatarTools#16]
When attempting to upload an avatar with the tools imported, fails to upload, creates a prefab_id prefab of the model in the assets and reports a: 
```
FileNotFoundException: C:/Users/SEVAST~1/AppData/Local/Temp/DefaultCompany/TestProject/prefab-id-v1_avtr_ca9d5709-7068-4f37-b5ae-31ab7dd2866a_8180208465.prefab.unity3d does not exist
System.IO.File.Move (System.String sourceFileName, System.String destFileName) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
```

Issue not present when tools are removed in the same project.

**Comment by rurre** [comment]
That happens when there's any errors. Check for other errors
