### ISSUE TITLE
Dynamic bones type conversion issue

### ISSUE THREAD

**Issue by Pursec** [rurre/PumkinsAvatarTools#17]
Upon importing greeted with script compliation error: 

```
Assets\PumkinsAvatarTools\Scripts\Editor\PumkinsAvatarTools.cs(5209,50): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<DynamicBoneCollider>' to 'System.Collections.Generic.List<DynamicBoneColliderBase>'
```

**Comment by rurre** [comment]
It's a known issue.
Try going to Edit > Project Settings > Player > Other Settings > Scripting Define Symbols and removing PUMKIN_DBONES and/or PUMKIN_OLD_DBONES
If you need help, it's better to join the discord and ask there. It's faster.
