### ISSUE TITLE
Error after importing unitypackage

### ISSUE THREAD

**Issue by MushyNibbles** [rurre/PumkinsAvatarTools#18]
After importing the package, I was given the error:

`Assets\PumkinsAvatarTools\Scripts\Editor\PumkinsAvatarTools.cs(6838,81): error CS0117: 'LogType' does not contain a definition for 'Log'`

I've tried using older versions from the discord, but I still get the same error. Looking through the FAQ on the discord didn't show anything relevant to my issue either.

**Comment by rurre** [comment]
Never seen this happen before. Will need to investigate.
LogType is a standard unity thing, it should be there.

What's your unity version?
________________________________

**Comment by MushyNibbles** [comment]
My current Unity version is 2018.4.20f1

**Comment by rurre** [comment]
Could you hop by my discord or DM me at Pumkin#9524 (nitro tag expired so it's wrong everywhere else) so we could troubleshoot it?

**Comment by rurre** [comment]
In the end the issue was conflicts with https://booth.pm/en/items/1564788
Unfortunately, they defined a type in the global namespace that conflict with a unity type. Can't do much here but replace all my logger calls, which I may or may not do at some point.
