### ISSUE TITLE
If GameObject is disabled, copied hierarchy is also disabled

### ISSUE THREAD

**Issue by tschaerni** [rurre/PumkinsAvatarTools#22]
Hi, thanks for your awesome tools. I have just one problem that is easy reproduceable, but really annoying:

If I copy everything over from one avatar to the other, and there are disabled GameObjects, if those GameObjects have other Objects underneath them, they get copied, but get also disabled (but they are enabled in the source hierarchy).
That makes it really annoying if you use that for logic or similar things.

I hope it's not a limitation of the Tools, and just a bug :/ 

Cheers
- tschaerni

**Comment by rurre** [comment]
Sounds like a bug. I might have overlooked this when I added code to disable game objects that were disabled at the source. It used to always copy everything as enabled. I'll try to fix this in the next update

**Comment by tschaerni** [comment]
Good to hear, I'm looking forward to your bugfix, because it's getting more and more annoying the more complex my Avatars become ;)

Cheers
- tschaerni

**Comment by rurre** [comment]
Fixed. Will be out in the next update later today. Thanks!

**Comment by tschaerni** [comment]
Thanks!
You do a great job mate (:
