### ISSUE TITLE
Copy of VRC Avatar Descriptor is sometimes borked

### ISSUE THREAD

**Issue by tschaerni** [rurre/PumkinsAvatarTools#24]
Hi, again ;)

I found another bug, it's not that easy reproducable, but it happend several times by now. If you copy the VRC Avatar Descriptor over, it sometimes messes up the Animation Layer settings under Playable Layers. It basically messes up the Descriptor it self, not only the settings. I'm not sure if its just a cosmetic problem with the UI, or the descriptor script it self...

I have some screenshots, the upper one is the original, the second one is the copied version.

![pumkin](https://user-images.githubusercontent.com/5721315/94975222-467b4a00-0511-11eb-877c-5108a648f0ca.png)

Cheers
- tscherni

**Comment by rurre** [comment]
That's weird, I've seen it happen as well. Gonna need to investigate

**Comment by tschaerni** [comment]
Could be related to and/or be that bug in the SDK itself: [VRChat canny](https://vrchat.canny.io/sdk-bug-reports/p/sdk202009250008-switching-a-rig-from-generic-to-the-humanoid-rig-type-causes-dup)

Need to test that, to be sure. In that case it's not a bug of the Avatar Tools

**Comment by rurre** [comment]
Interesting. That could be it


<http://aka.ms/weboutlook>

________________________________

**Comment by imagitama** [comment]
Happens to me too. My gesture layer is removed and I get 2 copies of my FX layer

**Comment by tschaerni** [comment]
I didn't had that problem since about a year... I thought that it was maybe fixed by VRChat themselfs in the SDK.
