### ISSUE TITLE
Breaks tool tabs and dynamic bones

### ISSUE THREAD

**Issue by Krypteck** [rurre/PumkinsAvatarTools#25]
If the latest version or even older versions are in my project dynamic bones no longer remembers settings and all the other tools I have disappear from the tabs at the top. If I delete the folder for pumkins tools the tabs return and dynamic bones returns to normal.

**Comment by rurre** [comment]
Any console errors? Got any other tools or scripts in your project? A tool from booth.pm is known to be incompatible
________________________________

**Comment by Krypteck** [comment]
I have [rero updater, xiexe, arktoon (from booth), thry, emote switch] in my tabs at the top. various other tools located in folders. from memory virtual lens is the only other booth item i have

**Comment by rurre** [comment]
Please join my discord so we could troubleshoot
________________________________
