### ISSUE TITLE
[Suggestion] Remove VRC and VRCSDK dependencies

### ISSUE THREAD

**Issue by NotAKidOnSteam** [rurre/PumkinsAvatarTools#26]
This tool will error without the VRChat SDK. This is inconvenient when using it in projects other than for VRChat as most of the functions in this tool are not specific to VRChat and the tool itself is incredibly useful even if it is tailored to VR avatar making. 

This would also make pumpkin tools work in ChilloutVR related unity projects without the need to also install VRChats SDK.

Proper ChilloutVR CCK support would also be nice but generalizing the tool would be amazing to do.

**Comment by rurre** [comment]
I'm currently rewriting everything to work without the vrc sdk and more.
I'll eventually support CVR as well but it's gonna take a while as there's a lot to do.

If you want to see development you can check the dev-updates channel on my discord or check the dev overhaul branch here on github
________________________________

**Comment by rurre** [comment]
Before that's done, I actually went ahead and removed dependencies in the WIP release of 0.9.2, which you can get on my discord!
