### ISSUE TITLE
[Suggestion] Copy Materials

### ISSUE THREAD

**Issue by RinLovesYou** [rurre/PumkinsAvatarTools#27]
This is an edge case, but losing an avatar always sucks.
I'd like to not go through the process of ripping my own avatar.
A simple tool, called LoadBundle, will let me spawn an instance of my vrchat avatar with every script present, it also includes every material. I am not able to save this however, so it is only a temporary solution that lets me copy over dynamic bones.
I find myself in this weird situation where i have to go through every material on the avatar, and copy > paste the settings to my reimported fbx. 

A nice feature to have would be adding the ability to copy over materials with the same names, just like dynamic bones etc.
Don't know if this is possible but if it is it'd be cool to have.

**Comment by rurre** [comment]
Materials are already being copied by slot, but not material settings. For that you need to use a shader that supports it.
And in case of load bundle those are temporary either way.
