### ISSUE TITLE
Temporarily show avatar without shaders

### ISSUE THREAD

**Issue by Bluscream** [rurre/PumkinsAvatarTools#28]
It would be neat if the tools had a toggle to replace all custom shaders with the default ones while enabled so one can preview how the own avatar would look to people without shaders enabled

**Comment by rurre** [comment]
Interesting idea. I'll look into it!

**Comment by Bluscream** [comment]
Thanks for checking that out ;3

**Comment by rurre** [comment]
Going to be included when I release the tool overhaul, whenever that's done. 
In the meantime you can try [this](https://github.com/rurre/VRChat-Fallback-Shader-Tester---Alpha--)

**Comment by Bluscream** [comment]
Awesome work, thank you <3

**Comment by Bluscream** [comment]
Any news on this?

**Comment by rurre** [comment]
It was added in one of the wip versions but didn't quite match the ingame look so was removed for now.

I would need someone to document exactly what fallback shaders keep and what they don't.
________________________________

**Comment by Bluscream** [comment]
Okay, thanks. please keep this issue updated on the status so i don't have to ask ^^
