### ISSUE TITLE
Cannot put Pumkins Tools into subfolder

### ISSUE THREAD

**Issue by Reploidsham** [rurre/PumkinsAvatarTools#29]
You cannot shove Pumkins into subfolders which I like to do for organization. Doing so causes the console to output errors about being unable to find namespaces for VRCSDK2, so it needs to always be in the assets root. 

Is it possible to resolve this? I was using .9b but could recreate it on the newest version.

**Comment by rurre** [comment]
Not sure, but generally it's not a good idea to move things like these as they it can often break them. I'll have a look anyway

**Comment by rurre** [comment]
Just tested it with latest WIP version (0.9.2) and SDK2 and it works fine for me when I put it into a subfolder

**Comment by rurre** [comment]
Should work in the next release either way
