### ISSUE TITLE
When the source and destination avatars have a common parent, Dynamic Bones are not copied correctly

### ISSUE THREAD

**Issue by dadenCKEP** [rurre/PumkinsAvatarTools#30]
## Expected Behavior
Root Game Object
├ Avatar A
│└ Object include Dynamic Bone 1
└ Avatar B
↓ Copy
Root Game Object
├ Avatar A
│└ Object include Dynamic Bone 1
└ Avatar B
　└ Object include Dynamic Bone 1

## Current Behavior
Root Game Object
├ Avatar A
│└ Object include Dynamic Bone 1
└ Avatar B
↓ Copy
Root Game Object
├ Avatar A
│└ Object include Dynamic Bone 1
└ Avatar B
　└ Avatar A
　　└Object include Dynamic Bone 1

## Possible Solution
Perhaps there is a problem with  `FindTransformInAnotherHierarchy()` or `CopyAllDynamicBonesNew()`.

## Steps to Reproduce
Run a copy with the same hierarchy as `Current Behavior`.

## Context (Environment)
Use latest SDK3(Avatars), latest Dynamic Bones, PumkinsAvatarTools v0.19b

--------
This problem can be solved by changing the avatar location, but I've heard that v0.9.2b will allow this tool to be used in UDON world, so I'll let you know this.

**Comment by rurre** [comment]
Yeah this is currently a limitation on how game object hierarchy is searched to cppy.
I'll rewrite it sometime to support place but for now it's recommended to not have avatars parented to anything.

**Comment by rurre** [comment]
This should be fixed now
