### ISSUE TITLE
Missing options since updating

### ISSUE THREAD

**Issue by r2dbk** [rurre/PumkinsAvatarTools#32]
Since updating from 0.9.1 to 0.9.2 I found that several options under the avatar section are missing, as well as copying components does not work like it used it.

![image](https://user-images.githubusercontent.com/78674945/107137415-34dfef80-68c1-11eb-81b0-3bb5dea97f50.png)

**Comment by rurre** [comment]
VRChat related options should be hidden if the SDK isn't detected. What SDK are you using?

**Comment by r2dbk** [comment]
VRCSDK3-AVATAR-2021.01.28.19.08

**Comment by rurre** [comment]
What are your script define symbols? Edit > Project Settings > Player > Other Options

![73e20ac995](https://user-images.githubusercontent.com/16716633/107139044-ed894b80-6920-11eb-8872-073f5d6011ec.png)

**Comment by r2dbk** [comment]
![image](https://user-images.githubusercontent.com/78674945/107139253-a8d4c480-68ce-11eb-9fac-365de0dd2f0d.png)

**Comment by rurre** [comment]
You still have a UDON define in there. Stuff's hidden for UDON projects. Just remove UDON from there.

**Comment by r2dbk** [comment]
That seems to have fixed it thanks a ton.
