### ISSUE TITLE
'Mesh prefab is missing, can't revert to default pose'

### ISSUE THREAD

**Issue by Benie76** [rurre/PumkinsAvatarTools#33]
Getting this with the latest version. Someone told me it might be because I need to set the T-Pose animation for my avatar as a prefab for the program, yet I've never had to do that before (nor would I know how to do such a thing outside of using UMotion).
I get this with Avatars 2.0 and 3.0.
![Unity_2021-03-20_21-17-35](https://user-images.githubusercontent.com/5062013/111955843-6bb04480-8ac0-11eb-9734-540843c37b43.png)
What the heck does it mean by 'mesh prefab'?

**Comment by rurre** [comment]
It gets the prefab of your avatar and reverts the positions of everything to that. 
If you don't have a mesh prefab then your fbx is the prefab.

If you don't have a fbx then what are you doing?

**Comment by Benie76** [comment]
I don't understand, I do have the fbx.. I mean, it's the only way to actually have an avatar.
Dunno what's wrong with it, or even how to find out the issue. Could someone possibly give me an idea?
I checked the rigging and it's correct. I've never touched it. ..The only thing I can think of is this program doesn't like how I have a hyphen in the name.

**Comment by rurre** [comment]
Maybe I broke something? I'll take a look at it later today.

**Comment by rurre** [comment]
There's now more options to reset pose that don't need a prefab.
