### ISSUE TITLE
VRC Spatial Audio Source component not copied w/Audio Source

### ISSUE THREAD

**Issue by Kretol** [rurre/PumkinsAvatarTools#36]
When using Copy Components with Audio Sources checked (along with all suboptions selected), although the sound gameobjects and Audio Source components are copied over, the VRC Spatial Audio Source component is not.  I do see that it is a Script, and presume there are issues copying scripts?  But I am unsure, so wanted to submit this as a potential issue just in case.

**Comment by rurre** [comment]
This has already been fixed but not released publicly yet.
You can grab the latest WIP release from the discord if you want the fix.

Thanks for the report!
________________________________
From: Kretol ***@***.***>
Sent: Friday, May 28, 2021 6:33:27 AM
To: rurre/PumkinsAvatarTools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rurre/PumkinsAvatarTools] VRC Spatial Audio Source component not copied w/Audio Source (#36)


When using Copy Components with Audio Sources checked (along with all suboptions selected), although the sound gameobjects and Audio Source components are copied over, the VRC Spatial Audio Source component is not. I do see that it is a Script, and presume there are issues copying scripts? But I am unsure, so wanted to submit this as a potential issue just in case.

**Comment by Kretol** [comment]
Oh, awesome!  Thank you!
