### ISSUE TITLE
3 Errors After Importing Unity Package

### ISSUE THREAD

**Issue by joy-1337** [rurre/PumkinsAvatarTools#39]
Assets\PumkinsAvatarTools\Scripts\Editor\Data\PumkinsAvatarInfo.cs(8,19): error CS0234: The type or namespace name 'Validation' does not exist in the namespace 'VRC.SDKBase' (are you missing an assembly reference?)

Assets\PumkinsAvatarTools\Scripts\Editor\Data\PumkinsAvatarInfo.cs(9,19): error CS0234: The type or namespace name 'Validation' does not exist in the namespace 'VRC.SDKBase' (are you missing an assembly reference?)

Assets\PumkinsAvatarTools\Scripts\Editor\Data\PumkinsAvatarInfo.cs(17,9): error CS0246: The type or namespace name 'AvatarPerformanceStats' could not be found (are you missing a using directive or an assembly reference?)

Not sure what any of this means, but its keeping me from finishing an avatar, upon importing an older, most likely depreciated version it crashes after exiting PlayMode.

**Comment by rurre** [comment]
Make sure you're on the latest SDK and unity Unity 2019.4.29f1.

**Comment by GenesisAria** [comment]
I get this issue with latest unity 2019.4.30f1

**Comment by brandonvdongen** [comment]
Getting these same 3 errors. using the latest sdk downloaded today. not sure what's causing it.

**Comment by rurre** [comment]
Should have been fixed by now
