### ISSUE TITLE
Copying Game Objects

### ISSUE THREAD

**Issue by TurtleP** [rurre/PumkinsAvatarTools#40]
Hi,

I know that this was mentioned ~3 years ago in #5, however I'm rather confused. On the latest release, there is no way to explicitly copy Game Objects in the way I think should be expected. My avatar has several things attached to the hands and they never get copied over to the new one. I end up having to manually copy and paste them into the new armature.

![image](https://user-images.githubusercontent.com/6239208/129065205-eaf0ca98-0430-465c-91b6-e41fd49c4424.png)

Could you please help me figure out the correct way to have these copied? I see there's a `Transforms` option, though to me that doesn't make as much sense as saying it's Game Objects.

**Comment by TurtleP** [comment]
So is it possible to add a Game Objects section that lets the user specify what they would like to copy?

I think that would be a great solution to this.

**Comment by rurre** [comment]
Possibly. Can you explain your use case/workflow?
What do your game objects do?
________________________________

**Comment by TurtleP** [comment]
They're just things that I happened to add in Unity and not Blender. The ring I have I can add easily, but I am not terribly familiar with making blend shape animations for the rest of the stuff for toggling them.

Granted that's my own fault for not relying on Blender, but I'm sure I'm not the only one who adds Game Objects like this via Unity only.

**Comment by rurre** [comment]
If it's a ring it's likely got a mesh renderer on it and you should be able to copy mesh renderers with game objects in their settings ticked.
________________________________

**Comment by TurtleP** [comment]
Hm, okay. I didn't think about that. I'll check it out and see how it goes.

**Comment by TurtleP** [comment]
Okay, just tried this out. Works perfectly! In all honesty, it sounds backwards when you think about the way this is, but regardless, thank you!
