### ISSUE TITLE
Copy Active State & Bounds

### ISSUE THREAD

**Issue by NotAKidOnSteam** [rurre/PumkinsAvatarTools#53]
I would like if the active state and bounding box of a gameobject were copied with the Copy Components function.

When I copy an avatars components I always have to go back and fix the bounds and active state.
I disable unused colliders/dynamic bone objects per outfit, so having to go through and fix that can be quite annoying and taxing.
I also set my bounds myself so I do not disappear at weird angles.

Please add the option to copy them instead.

**Comment by rurre** [comment]
Added copy active state to the latest wip (get it from my discord).
Will do bounds later as well.

**Comment by NotAKidOnSteam** [comment]
happy happy thank you!

**Comment by rurre** [comment]
Alright, added bounds copying as well as I've been doing it manually and getting just as annoyed at it.
