### ISSUE TITLE
lineup_wall.fbx has incorrect measurements for Feet/Inches

### ISSUE THREAD

**Issue by Nirv-git** [rurre/PumkinsAvatarTools#54]
The calculation from Meter to Feet is in decimal, but show it as Ft'In.

For example 1.5m shows 4'9, but that is actually 4'11

Attached is a fixed version with included finer graduations 
https://cdn.discordapp.com/attachments/384108535887298582/950278372989231164/lineup_wall_Fixed.fbx

**Comment by rurre** [comment]
Implemented! Thanks
