### ISSUE TITLE
Avatar Info PhysBone rankings are incorrect

### ISSUE THREAD

**Issue by dtupper** [rurre/PumkinsAvatarTools#59]
I didn't check any more than just this, but at least the PhysBone transform ranking is incorrect.

Check [here](https://docs.vrchat.com/docs/avatar-performance-ranking-system) for the correct values. 

In this case, the avatar has 84 PhysBone transforms, which marks it as a Medium (Good's threshhold is at 64, so <64 PB transforms on PC drops you to Medium).

Your Avatar Info panel incorrectly calls that a Good rank.

![image](https://user-images.githubusercontent.com/5649747/165009496-59e1b4dd-2a02-47da-935b-72e4d70decca.png)

**Comment by rurre** [comment]
It's grabbing the values and ranks out of the sdk so it was probably referencing the wrong thing. I'll have a look

**Comment by rurre** [comment]
Fixed, it was referencing physbone components instead.
