### ISSUE TITLE
Latest release 0.5.2b does not include _DependancyChecker.cs

### ISSUE THREAD

**Issue by ProbablePrime** [rurre/PumkinsAvatarTools#6]
The latest release does not include the dependency checker files so the ad-don fails to compile

**Comment by rurre** [comment]
Are you sure? It's there for me on v0.5.3b when importing.

**Comment by ProbablePrime** [comment]
Ahh looks like its not registering as a C# file: 
![image](https://user-images.githubusercontent.com/8791132/57663111-74bc5a80-75a7-11e9-8e57-72850d1d9d32.png)

**Comment by rurre** [comment]
That's really strange because it looks fine to me
![4e460a4ff1](https://user-images.githubusercontent.com/16716633/57667099-49169000-75fa-11e9-9965-d5d4ece5d3b6.png)

**Comment by Flame102** [comment]
ive been having this issue too. I have to delete it when upload time comes

**Comment by rurre** [comment]
That's really strange. Can you provide more info? Any errors in console? Does the file just have no extension when importing?

**Comment by ProbablePrime** [comment]
It has no extension when downloading

**Comment by ProbablePrime** [comment]
Specifically this URL: https://github.com/rurre/PumkinsAvatarTools/archive/0.5.2b.zip

Downloads a release where DependencyChecker has no extension. Downloading master or another release could be fine

**Comment by rurre** [comment]
I see, that's right. For some reason 0.5.2b doesn't include an extension for _DependencyChecker, and I've been looking at 0.5.3b instead. 
I don't seem to be able to edit that as it's not the latest release.

You should grab the latest one instead, or is there any reason you aren't using it?

**Comment by ProbablePrime** [comment]
That would be a UI hiccup on Github, its somehow harder to find the assets for the latest release. >.<

Ok we can close this. I'm sorry.
