### ISSUE TITLE
[Creator Companion] PhysBones & Contacts

### ISSUE THREAD

**Issue by NotAKidOnSteam** [rurre/PumkinsAvatarTools#62]
Pumpkin Avatar Tools cannot find the SDK when using a Creator Companion project. Breaks PhysBone and Contact copier.

![image](https://user-images.githubusercontent.com/37721153/169674368-353ae173-00a6-4c3c-a3ee-ffa5377db341.png)

https://github.com/rurre/PumkinsAvatarTools/blob/55437183a1beac624a741dd001b4f3cb6c1b510e/Scripts/Editor/_DependencyChecker.cs#L118-L136

**Comment by rurre** [comment]
I'll look into it over the weekend.

**Comment by rurre** [comment]
Now fixed
