### ISSUE TITLE
unity 2017.4.28f1

### ISSUE THREAD

**Issue by migero** [rurre/PumkinsAvatarTools#7]
PumkinsAvatarTools.cs(1182,42): error CS1061: Type `DynamicBone' does not contain a definition for `m_UpdateMode' and no extension method `m_UpdateMode' of type `DynamicBone' could be found. Are you missing an assembly reference?

**Comment by migero** [comment]
removing dTo.m_UpdateMode = dFrom.m_UpdateMode; 
on line 1182 fixes it and can copy dynamic bones

**Comment by rurre** [comment]
Which version of dynamic bones are you using? Can I have the file to take a look at it?

**Comment by rurre** [comment]
This should have been fixed now. Just grab the latest release!
