### ISSUE TITLE
(Bug) Copy Components

### ISSUE THREAD

**Issue by HartLeeKonnor** [rurre/PumkinsAvatarTools#74]
Seems like copying physbones from a similar model or in my case previously updated prefab isnt working.

**Comment by rurre** [comment]
There have been some issues recently. Try unchecking particle copying and blendshape values in the skinned mesh renderer copier. (Any kind of errors can interrupt the copying process).

**Comment by HartLeeKonnor** [comment]
Still buggy, good luck on the great work you do tho. I love your unity tool.

**Comment by rurre** [comment]
Try latest release
