### ISSUE TITLE
Bad physbone copy value

### ISSUE THREAD

**Issue by Kieaer** [rurre/PumkinsAvatarTools#79]
![image](https://user-images.githubusercontent.com/44261958/209042644-a8674a34-a1ba-40d2-be8a-6311e1a96fd8.png)
Orignal (Karin)

![image](https://user-images.githubusercontent.com/44261958/209042609-e0a64ab3-4c1e-4c8f-aa8b-43ec36493b9f.png)
New avatar (Karin blender edit)

**Comment by rurre** [comment]
Never seen that issue before, that's weird

**Comment by Kieaer** [comment]
@rurre Is there a way to enable the debug log? There is only Success without any warning messages in the console.

**Comment by rurre** [comment]
In settings (top right) you can enable verbose logging, but I don't know if it will give you any more info.
________________________________

**Comment by Shiboneko** [comment]
I have a similiar issue, probably related to this.
The floating point disappears on my avatar.
The original value is 0.15 and 0.54
But it copies over 15 and 54
![grafik](https://user-images.githubusercontent.com/5616811/209541162-49151c1e-89db-4c1a-9991-c8ed7a3f5293.png)

The same happens to collider in physbones

![grafik](https://user-images.githubusercontent.com/5616811/209541416-02d04ffb-186c-4636-888a-1ff924ee5f1c.png)

**Comment by rurre** [comment]
Okay, that's definitely not intended. What happens if you untick adjust scale?
________________________________

**Comment by Shiboneko** [comment]
Hi,
that fixes it. Ok.

What does this option actually do?

**Comment by rurre** [comment]
It's supposed to fix the difference between avatars with different export settings. Which does in fact cause a difference of 100.
________________________________

**Comment by Shiboneko** [comment]
Hm, ok.
I know that exporting objects into unity is it's own magic. I asked a few people about  this, and everyone gave me a different answer. Depending on their settings and program.
Sadly I can't tell if my source and destination have different export settings ^^

But thank you!

**Comment by rurre** [comment]
Default blender export settings cause the Armature object of your avatar to be of scale 100,100,100, which makes all values for stuff like physbone collider radius have to be divided by 100.

Setting the scaling to fbx all in blender's export options fixes this and causes the armature to have a scale of 1,1,1 as it should.
________________________________

**Comment by rurre** [comment]
Adjust scale is now unticked by default in all copiers. Might look into fixing it at some point.
