### ISSUE TITLE
error CS0246: The type or namespace name 'RootMotion' could not be found

### ISSUE THREAD

**Issue by chrisrichardz** [rurre/PumkinsAvatarTools#83]
Assets\PumkinsAvatarTools\Scripts\Editor\Copiers\LegacyCopier.cs(34,7): error CS0246: The type or namespace name 'RootMotion' could not be found (are you missing a using directive or an assembly reference?)

Don't know what does it means

**Comment by rurre** [comment]
It's expecting you to have FinalIK imported in your project for some reason.
`Edit > Project Settings > Player > Other Settings > Script Define Symbols` and remove PUMKIN_FINALIK if it's there.

**Comment by rurre** [comment]
The PUMKIN_FINALIK define is no longer used so should be fixed now anyway.
