### ISSUE TITLE
 error CS0246: The type or namespace name 'VRCPhysBone' could not be found

### ISSUE THREAD

**Issue by oragres** [rurre/PumkinsAvatarTools#85]
Hello,
Ive got the problem that the last working version is 1.1.1. Every version afterwards is not working anymore and i just get this error.
VRCSDK is latest release

Full Error message (Repeated like 3 times)
Assets\PumkinsAvatarTools\Scripts\Editor\PumkinsAvatarTools.cs(4343,84): error CS0246: The type or namespace name 'VRCPhysBone' could not be found (are you missing a using directive or an assembly reference?)

**Comment by rurre** [comment]
There seems to be an issue currently. Go into Edit > Project Settings > Player > Other Settings > Script Define Symbols and add PUMKIN_PBONES.
If you have something in there already it should be separated by a semicolon. Like this:
stuff; whatever; PUMIN_PBONES
________________________________
From: oragres ***@***.***>
Sent: 01 April 2023 19:42
To: rurre/PumkinsAvatarTools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rurre/PumkinsAvatarTools] error CS0246: The type or namespace name 'VRCPhysBone' could not be found (Issue #85)


Hello,
Ive got the problem that the last working version is 1.1.1. Every version afterwards is not working anymore and i just get this error.
VRCSDK is latest release

Full Error message (Repeated like 3 times)
Assets\PumkinsAvatarTools\Scripts\Editor\PumkinsAvatarTools.cs(4343,84): error CS0246: The type or namespace name 'VRCPhysBone' could not be found (are you missing a using directive or an assembly reference?)

**Comment by oragres** [comment]
I assume you meant PUMKIN_PBONES but that one is already there

"PUMKIN_PBONES;PUMKIN_DBONES;VRC_SDK_VRCSDK3;DYNAMICBONES_EXISTS;UNITY_POST_PROCESSING_STACK_V2;UDON;UDONSHARP;AUDIOLINK"

**Comment by rurre** [comment]
Assuming this got fixed since dynamic bones no longer use the PUMKIN_PBONES define.
