### ISSUE TITLE
Make it addable to VRC Community Repositories

### ISSUE THREAD

**Issue by ghost** [rurre/PumkinsAvatarTools#87]
![image](https://user-images.githubusercontent.com/103474655/231005616-e5f37bf4-7604-46cc-b94e-b77a1bc438da.png)

**Comment by Koyoinu** [comment]
Yeah the Json doesnt work

**Comment by rurre** [comment]
I'll set it up eventually.

**Comment by rurre** [comment]
Was added a while ago, I forgot to go through these.
