### ISSUE TITLE
use reverse domain name for package name (and asmdef)

### ISSUE THREAD

**Issue by TayouVR** [rurre/PumkinsAvatarTools#88]
According to official documentation, It's recommended to use reverse domain name for package name.
This is mandatory for [OpenUPM publishing](https://github.com/openupm/openupm/pull/3910)

[vcc.docs.vrchat.com/guides/convert-unitypackage/#package-maker-tool](https://vcc.docs.vrchat.com/guides/convert-unitypackage/#package-maker-tool)

> The standard practice for is reverse domain notation like com.vrchat.packagename, using a domain you own.

Most other projects use reverse domain name, `<user>.github.io` is regarded to be owned by github user so I think we should use `io.github.rurre` as prefix.

See also: https://docs.unity3d.com/2019.4/Documentation/Manual/cus-naming.html

**Comment by rurre** [comment]
Will do in the next update later today. Thanks!
