### ISSUE TITLE
[Feature Request][Copy Components] Copy VRCFury components & generally any generic scripts

### ISSUE THREAD

**Issue by TayouVR** [rurre/PumkinsAvatarTools#91]
I always thought "Other" would copy any other script, but reading through it, it seems that is only for VRM Spring bones, not actually for anything else.
Would it be viable to copy *any* script?

or to support copying VRCFury specific components? (the types of components may change in the future, so checking namespace might be the easiest way to go on about it)

**Comment by KrazenLabs** [comment]
VRCFury copying would really be appreciated as it is becoming more and more common and with things like SPS I see usage increasing further and leading to more VRCF components ending up deep insight armatures, etc.

**Comment by kklouzal** [comment]
Yes, quite a bother VRCFury components aren't copied..

**Comment by rurre** [comment]
Added support for this today. You can grab the WIP from my discord's WIP-releases channel. 

Gonna push the update to github and VCC a little later if all goes well.

**Comment by AraHaan** [comment]
@rurre did it go well?

**Comment by rurre** [comment]
Yeah, this was released today. You can define your own component types in a json file and vrcfury is included by default. Check the external section in the component copier.
________________________________

**Comment by KrazenLabs** [comment]
Awesome work! Thank you so much!

**Comment by AraHaan** [comment]
Nice
