### ISSUE TITLE
Use package version for version string in UI

### ISSUE THREAD

**Issue by TayouVR** [rurre/PumkinsAvatarTools#96]
I saw in the code, that the version is encoded in some class
This issue is more a reminder for me to open a PR to use the package manifest to extract the version.
I have done so in a few packages myself, so its just a matter of finding the right time to do it.

(technical): you can get the package manifest through its guid in asset database, json deserialize it, and take the version string/number that way. then its only one place to bump the number.

**Comment by rurre** [comment]
Yeah it's in the strings class. The code is really old at this point.

**Comment by rurre** [comment]
Done in the next update
