### ISSUE TITLE
Pumpkin tool does not seem to play well with VRC descriptor tools

### ISSUE THREAD

**Issue by DonovanPhoenix** [rurre/PumkinsAvatarTools#97]
I am new to using this toolset, so nit sure if this is a fixable bug, 

In the vrc Descriptor you get View>edit, this is no longer working once i installed Pumpkin, but if i go to Pumpkin Tools > Avatar > Edit viewpoint, then it is working, so it seems that this is overriding the original  Descriptor script? also seems to do this with other things like eye-look ect...

**Comment by rurre** [comment]
I haven't tested anything with the new sdk so it's likely it's incompatible.

**Comment by rurre** [comment]
Works fine for me. Make sure your editor gizmos are enabled
![image](https://github.com/rurre/PumkinsAvatarTools/assets/16716633/1c852bf6-3377-45d2-9589-508ca402fdb9)
